### ISSUE TITLE
Load URLs straight to marker location

### ISSUE THREAD

**Issue by futuresoup** [smartercleanup/platform#303]
URLs such as http://heyduwamish.org/12th-and-elmgrove always load the default coordinates of heyduwamish.org first, then after a while it jumps over to the actual location.

**Is there any way we can bypass this?**

It would give us a big bump in usability.

**Comment by futuresoup** [comment]
Might be a tough fix. Better approach is to make site load faster so user doesn't notice this redirect.

**Comment by goldpbear** [comment]
Agreed this is a complex fix. Because of the order in which things happen when the page first load, I think jumping immediately to a marker location would be a significant refactor.

**Comment by goldpbear** [comment]
I believe this is addressed by #593.

**Comment by futuresoup** [comment]
Nah, still appears to go to the default homepage location then jumps over to the landmark location.

See here - https://heyduwamish.org/concord - should go straight to the elementary school, but actually goes to the river first then jump to the school

**Comment by goldpbear** [comment]
I think #593 improved the delay slightly, but didn't completely remove it. When we refactor landmark urls to have an id that can be directly referenced on the server, we can expect loading to be comparable to that of current place urls (e.g. `/trees/243`). The delay occurs because we have to completely load all datasets, then search them one by one for the landmark-style url until we find it.

Referencing #879 here.
